---
# tasks file for wireguard
- name: Make sure firewalld is installed
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Download PiVPN install script
  ansible.builtin.get_url:
    url: https://install.pivpn.io
    dest: ./install.sh
    mode: "0750"

- name: Create PiVPN unattended options file
  ansible.builtin.template:
    src: unattended_wireguard.conf.j2
    dest: ./unattended_wireguard.conf
    mode: "0640"

- name: Install PiVPN
  ansible.builtin.command:
    cmd: ./install.sh --unattended ./unattended_wireguard.conf
    creates: /usr/local/bin/pivpn

- name: Open firewall port 51820
  ansible.posix.firewalld:
    port: "{{ wireguard_port }}/udp"
    permanent: true
    state: enabled
  notify:
    - restart_firewalld

- name: Allow masquerade
  ansible.posix.firewalld:
    masquerade: true
    permanent: true
    state: enabled
  notify:
    - restart_firewalld
